#cloud-config
packages:
  - jq

write_files:
  - path: /etc/vault.d/vault.conf
    content: ${vault_conf}
    permissions: '0644'
    owner: vault:vault
    encoding: b64
  - path: /etc/environment
    content: |
      VAULT_ADDR=http://${ip_address}:8200
    append: true

runcmd:
  - systemctl enable vault
  - systemctl restart vault
  - payload=$(vault operator init --format=json)
  - echo $payload >> /home/grant/vault.json
  - vault operator unseal $(echo $payload | jq -r .unseal_keys_b64[0])
  - vault operator unseal $(echo $payload | jq -r .unseal_keys_b64[1])
  - vault operator unseal $(echo $payload | jq -r .unseal_keys_b64[2])